name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@16b9408
      - run: ./build.sh

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: ./test.sh
