name: CI

on: [push]

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@16b9408
      - name: Build
        run: ./build.sh
      - name: Test
        run: ./test.sh
